[gcp_service_account]
type = "service_account"
project_id = "airflow-sheets-473117"
private_key_id = "50ac73d76c15f390b2f45746f749be3b19283c05"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBg... (tu llave completa) ...\n-----END PRIVATE KEY-----\n"
client_email = "clients@airflow-sheets-473117.iam.gserviceaccount.com"
client_id = "107451548924701567605"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/clients%40airflow-sheets-473117.iam.gserviceaccount.com"